
package com.workpoint.icpak.server.navintegration;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Online_Member_Payments_Port", targetNamespace = "urn:microsoft-dynamics-schemas/page/online_member_payments")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OnlineMemberPaymentsPort {


    /**
     * 
     * @param transactionCode
     * @return
     *     returns schemas.dynamics.microsoft.page.online_member_payments.OnlineMemberPayments
     */
    @WebMethod(operationName = "Read", action = "urn:microsoft-dynamics-schemas/page/online_member_payments:Read")
    @WebResult(name = "Online_Member_Payments", targetNamespace = "urn:microsoft-dynamics-schemas/page/online_member_payments")
    @RequestWrapper(localName = "Read", targetNamespace = "urn:microsoft-dynamics-schemas/page/online_member_payments", className = "schemas.dynamics.microsoft.page.online_member_payments.Read")
    @ResponseWrapper(localName = "Read_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/online_member_payments", className = "schemas.dynamics.microsoft.page.online_member_payments.ReadResult")
    public OnlineMemberPayments read(
        @WebParam(name = "Transaction_Code", targetNamespace = "urn:microsoft-dynamics-schemas/page/online_member_payments")
        String transactionCode);

    /**
     * 
     * @param recId
     * @return
     *     returns schemas.dynamics.microsoft.page.online_member_payments.OnlineMemberPayments
     */
    @WebMethod(operationName = "ReadByRecId", action = "urn:microsoft-dynamics-schemas/page/online_member_payments:ReadByRecId")
    @WebResult(name = "Online_Member_Payments", targetNamespace = "urn:microsoft-dynamics-schemas/page/online_member_payments")
    @RequestWrapper(localName = "ReadByRecId", targetNamespace = "urn:microsoft-dynamics-schemas/page/online_member_payments", className = "schemas.dynamics.microsoft.page.online_member_payments.ReadByRecId")
    @ResponseWrapper(localName = "ReadByRecId_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/online_member_payments", className = "schemas.dynamics.microsoft.page.online_member_payments.ReadByRecIdResult")
    public OnlineMemberPayments readByRecId(
        @WebParam(name = "recId", targetNamespace = "urn:microsoft-dynamics-schemas/page/online_member_payments")
        String recId);

    /**
     * 
     * @param filter
     * @param setSize
     * @param bookmarkKey
     * @return
     *     returns schemas.dynamics.microsoft.page.online_member_payments.OnlineMemberPaymentsList
     */
    @WebMethod(operationName = "ReadMultiple", action = "urn:microsoft-dynamics-schemas/page/online_member_payments:ReadMultiple")
    @WebResult(name = "ReadMultiple_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/online_member_payments")
    @RequestWrapper(localName = "ReadMultiple", targetNamespace = "urn:microsoft-dynamics-schemas/page/online_member_payments", className = "schemas.dynamics.microsoft.page.online_member_payments.ReadMultiple")
    @ResponseWrapper(localName = "ReadMultiple_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/online_member_payments", className = "schemas.dynamics.microsoft.page.online_member_payments.ReadMultipleResult")
    public OnlineMemberPaymentsList readMultiple(
        @WebParam(name = "filter", targetNamespace = "urn:microsoft-dynamics-schemas/page/online_member_payments")
        List<OnlineMemberPaymentsFilter> filter,
        @WebParam(name = "bookmarkKey", targetNamespace = "urn:microsoft-dynamics-schemas/page/online_member_payments")
        String bookmarkKey,
        @WebParam(name = "setSize", targetNamespace = "urn:microsoft-dynamics-schemas/page/online_member_payments")
        int setSize);

    /**
     * 
     * @param key
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "IsUpdated", action = "urn:microsoft-dynamics-schemas/page/online_member_payments:IsUpdated")
    @WebResult(name = "IsUpdated_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/online_member_payments")
    @RequestWrapper(localName = "IsUpdated", targetNamespace = "urn:microsoft-dynamics-schemas/page/online_member_payments", className = "schemas.dynamics.microsoft.page.online_member_payments.IsUpdated")
    @ResponseWrapper(localName = "IsUpdated_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/online_member_payments", className = "schemas.dynamics.microsoft.page.online_member_payments.IsUpdatedResult")
    public boolean isUpdated(
        @WebParam(name = "Key", targetNamespace = "urn:microsoft-dynamics-schemas/page/online_member_payments")
        String key);

    /**
     * 
     * @param key
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetRecIdFromKey", action = "urn:microsoft-dynamics-schemas/page/online_member_payments:GetRecIdFromKey")
    @WebResult(name = "GetRecIdFromKey_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/online_member_payments")
    @RequestWrapper(localName = "GetRecIdFromKey", targetNamespace = "urn:microsoft-dynamics-schemas/page/online_member_payments", className = "schemas.dynamics.microsoft.page.online_member_payments.GetRecIdFromKey")
    @ResponseWrapper(localName = "GetRecIdFromKey_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/online_member_payments", className = "schemas.dynamics.microsoft.page.online_member_payments.GetRecIdFromKeyResult")
    public String getRecIdFromKey(
        @WebParam(name = "Key", targetNamespace = "urn:microsoft-dynamics-schemas/page/online_member_payments")
        String key);

    /**
     * 
     * @param onlineMemberPayments
     */
    @WebMethod(operationName = "Create", action = "urn:microsoft-dynamics-schemas/page/online_member_payments:Create")
    @RequestWrapper(localName = "Create", targetNamespace = "urn:microsoft-dynamics-schemas/page/online_member_payments", className = "schemas.dynamics.microsoft.page.online_member_payments.Create")
    @ResponseWrapper(localName = "Create_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/online_member_payments", className = "schemas.dynamics.microsoft.page.online_member_payments.CreateResult")
    public void create(
        @WebParam(name = "Online_Member_Payments", targetNamespace = "urn:microsoft-dynamics-schemas/page/online_member_payments", mode = WebParam.Mode.INOUT)
        Holder<OnlineMemberPayments> onlineMemberPayments);

    /**
     * 
     * @param onlineMemberPaymentsList
     */
    @WebMethod(operationName = "CreateMultiple", action = "urn:microsoft-dynamics-schemas/page/online_member_payments:CreateMultiple")
    @RequestWrapper(localName = "CreateMultiple", targetNamespace = "urn:microsoft-dynamics-schemas/page/online_member_payments", className = "schemas.dynamics.microsoft.page.online_member_payments.CreateMultiple")
    @ResponseWrapper(localName = "CreateMultiple_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/online_member_payments", className = "schemas.dynamics.microsoft.page.online_member_payments.CreateMultipleResult")
    public void createMultiple(
        @WebParam(name = "Online_Member_Payments_List", targetNamespace = "urn:microsoft-dynamics-schemas/page/online_member_payments", mode = WebParam.Mode.INOUT)
        Holder<OnlineMemberPaymentsList> onlineMemberPaymentsList);

    /**
     * 
     * @param onlineMemberPayments
     */
    @WebMethod(operationName = "Update", action = "urn:microsoft-dynamics-schemas/page/online_member_payments:Update")
    @RequestWrapper(localName = "Update", targetNamespace = "urn:microsoft-dynamics-schemas/page/online_member_payments", className = "schemas.dynamics.microsoft.page.online_member_payments.Update")
    @ResponseWrapper(localName = "Update_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/online_member_payments", className = "schemas.dynamics.microsoft.page.online_member_payments.UpdateResult")
    public void update(
        @WebParam(name = "Online_Member_Payments", targetNamespace = "urn:microsoft-dynamics-schemas/page/online_member_payments", mode = WebParam.Mode.INOUT)
        Holder<OnlineMemberPayments> onlineMemberPayments);

    /**
     * 
     * @param onlineMemberPaymentsList
     */
    @WebMethod(operationName = "UpdateMultiple", action = "urn:microsoft-dynamics-schemas/page/online_member_payments:UpdateMultiple")
    @RequestWrapper(localName = "UpdateMultiple", targetNamespace = "urn:microsoft-dynamics-schemas/page/online_member_payments", className = "schemas.dynamics.microsoft.page.online_member_payments.UpdateMultiple")
    @ResponseWrapper(localName = "UpdateMultiple_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/online_member_payments", className = "schemas.dynamics.microsoft.page.online_member_payments.UpdateMultipleResult")
    public void updateMultiple(
        @WebParam(name = "Online_Member_Payments_List", targetNamespace = "urn:microsoft-dynamics-schemas/page/online_member_payments", mode = WebParam.Mode.INOUT)
        Holder<OnlineMemberPaymentsList> onlineMemberPaymentsList);

    /**
     * 
     * @param key
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "Delete", action = "urn:microsoft-dynamics-schemas/page/online_member_payments:Delete")
    @WebResult(name = "Delete_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/online_member_payments")
    @RequestWrapper(localName = "Delete", targetNamespace = "urn:microsoft-dynamics-schemas/page/online_member_payments", className = "schemas.dynamics.microsoft.page.online_member_payments.Delete")
    @ResponseWrapper(localName = "Delete_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/online_member_payments", className = "schemas.dynamics.microsoft.page.online_member_payments.DeleteResult")
    public boolean delete(
        @WebParam(name = "Key", targetNamespace = "urn:microsoft-dynamics-schemas/page/online_member_payments")
        String key);

}
